# --- Parameters ---

# File paths
INPUT_YAML_FILE: 'metadata/room2.yaml'  # <<<--- Set this to your YAML file path
# INPUT_PGM_FILE derived from YAML
OUTPUT_RASTER_FLOORPLAN_FILE: 'floorplan_raster_room2.png' # PNG output
OUTPUT_VECTOR_FLOORPLAN_FILE: 'floorplan_vector_room2.svg' # SVG output
# Optional debug output paths
OUTPUT_PREPROCESSED_FILE: 'debug_preprocessed_room2.png'
OUTPUT_CLEANED_FILE: 'debug_cleaned_room2.png'
OUTPUT_RAW_LINES_FILE: 'debug_raw_lines_room2.png'
OUTPUT_MERGED_LINES_FILE: 'debug_merged_lines_room2.png' # Shows merged lines

# --- Default values (used if YAML loading fails) ---
DEFAULT_RESOLUTION: 0.01 # meters/pixel
DEFAULT_NEGATE: 0
DEFAULT_ORIGIN: [-8.98, -10.5, 0.0] # Default origin

# --- Parameters defined in METERS (converted to pixels) ---
MIN_LINE_LENGTH_METERS: 0.20  # Allow shorter segments initially for merging
MAX_LINE_GAP_METERS: 0.10   # Allow slightly larger gaps if merging works well

# --- Parameters defined in PIXELS or independent of resolution ---
# PGM Input pixel values (Typical ROS map_server values)
UNKNOWN_PGM_VAL: 205
OCCUPIED_PGM_VAL: 0
FREE_PGM_VAL: 254

# Target values AFTER preprocessing
OCCUPIED_VAL: 0    # Black for occupied
FREE_VAL: 255      # White for free

# Morphological operations
MORPH_OPEN_KERNEL_SIZE: [3, 3] # Noise removal
MORPH_CLOSE_KERNEL_SIZE: [5, 5] # Gap closing

# Hough Line Transform Parameters 
HOUGH_RHO: 1
HOUGH_THETA: 1
HOUGH_THRESHOLD: 30 # Lower threshold might detect more segments for merging

MERGE_ANGLE_THRESHOLD_DEG: 5.0  # Max angle difference to consider lines collinear
# Max distance between endpoints of segments to consider merging (pixels)
MERGE_DISTANCE_THRESHOLD_PX: 15

# Output drawing colors (BGR) / SVG Styles
WALL_COLOR_BGR: [255,255,255]       
BACKGROUND_COLOR_BGR: [66, 55, 20]
WALL_THICKNESS_PX: 2
SVG_WALL_COLOR: "black"
SVG_STROKE_WIDTH: "2"